### ISSUE TITLE
Cannot resolve module

### ISSUE THREAD

**Issue by dev101** [auth0/webtask-bundle#18]
It's a known issue that using core js methods (like `JSON.stringify` or `Object.keys`) in your webtask is causing `Cannot resolve module` webpack errors.

As @ggoodman  suggested on [slack](https://webtask-chat.slack.com/archives/general/p1467064080000021), commenting out [babel-plugin-transform-runtime](https://github.com/auth0/webtask-bundle/blob/master/lib/configureWebpack.js#L35) helps to resolve this error.

But it's still in master branch, so people have this errors, and it seems like some guidance or action is needed to prevent this.

FYI, the errors look like this:
`>wt-bundle webtask.js --output ./build/webtask.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/keys' in \dir\webtask\morph\lib
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/keys' in \dir\webtask\morph\lib
    at C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\webpack\lib\Compilation.js:229:38
    at onDoneResolving (C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\webpack\lib\NormalModuleFactory.js:29:20)
    at C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\webpack\lib\NormalModuleFactory.js:85:20
    at C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\webpack\node_modules\async\lib\async.js:726:13
    at C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\webpack\node_modules\async\lib\async.js:241:17)
    at C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\webpack\node_modules\async\lib\async.js:723:17
    at C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\webpack\node_modules\async\lib\async.js:167:37
    at C:\Users\dev101\AppData\Roaming\npm\node_modules\webtask-bundle\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19`

**Comment by ggoodman** [comment]
Fixed in 011456e172dfbf545e0925d5879c78634d0f3fcf.
