### ISSUE TITLE
add support for async/await

### ISSUE THREAD

**Issue by mitel** [auth0/webtask-bundle#23]
Hello, 
it would be nice to have support for async/await in Webtasks.
If we use babel/transform-async-to-generator, async functions will be compiled to generator functions, which are supported natively by node 4.4.5. 
the only drawback would be that Uglify.js will not be able to minify code with generator functions.

```
presets: [
    // includes transform-async-to-generator that will transform async to 
    // generator functions supported natively on node v4
    require.resolve('babel-preset-es2017'),
    require.resolve('babel-preset-es2016')
],
// babel-preset-es2015 without transform-regenerator as
// we're going to use the native suport of node for generator functions
plugins: [
    require.resolve('babel-plugin-check-es2015-constants'),
    require.resolve('babel-plugin-transform-es2015-arrow-functions'),
    require.resolve('babel-plugin-transform-es2015-block-scoping'), 
    require.resolve('babel-plugin-transform-es2015-block-scoped-functions'), 
    require.resolve('babel-plugin-transform-es2015-classes'), 
    require.resolve('babel-plugin-transform-es2015-computed-properties'), 
    require.resolve('babel-plugin-transform-es2015-destructuring'), 
    require.resolve('babel-plugin-transform-es2015-duplicate-keys'),  
    require.resolve('babel-plugin-transform-es2015-for-of'), 
    require.resolve('babel-plugin-transform-es2015-function-name'), 
    require.resolve('babel-plugin-transform-es2015-literals'),
    require.resolve('babel-plugin-transform-es2015-modules-commonjs'),
    require.resolve('babel-plugin-transform-es2015-object-super'),
    require.resolve('babel-plugin-transform-es2015-parameters'),
    require.resolve('babel-plugin-transform-es2015-shorthand-properties'),
    require.resolve('babel-plugin-transform-es2015-spread'),
    require.resolve('babel-plugin-transform-es2015-sticky-regex'),
    require.resolve('babel-plugin-transform-es2015-template-literals'),
    require.resolve('babel-plugin-transform-es2015-typeof-symbol'),
    require.resolve('babel-plugin-transform-es2015-unicode-regex'),
    require.resolve('babel-plugin-transform-object-rest-spread')
]
```

**Comment by mitel** [comment]
UPDATE:
using Babili minification i'm now able to minify ES6 code with generator functions:

```
if (options.minify) {
        const minifyOptions = typeof options.minify === 'object'
            ?   options.minify
            :   {};
        
        // config.plugins.push(new Webpack.optimize.UglifyJsPlugin(minifyOptions));
        const babiliPluginOptions = { 
            babili:  [
                require.resolve('babel-preset-babili'), {
                    "mangle": {
                        "blacklist": { 
                            "ctx": true, 
                            "cb": true
                        },
                        // "keepFnName": true
                    },
                    // disables babel-plugin-minify-dead-code-elimination
                    // Inlines bindings when possible. Tries to evaluate expressions 
                    // and prunes unreachable as a result.
                    "deadcode": false,
                }
            ]
        }
        const opts = Object.assign({}, minifyOptions, babiliPluginOptions);
        config.plugins.push(new BabiliPlugin(opts));
    }
```

**Comment by pencilcheck** [comment]
How do you setup with webtask-bundle? Is there a tutorial on this?

**Comment by ggoodman** [comment]
@pencilcheck `webtask-bundle` exists primarily as a library that provides the `--bundle` functionality to `wt-cli` and is not intended to be directly consumed.

**Comment by mrwillis** [comment]
Yes this would be incredibly helpful. I've just realized that I don't think I can use `regeneratorRuntime` either :( from [here](https://tehsis.github.io/webtaskio-canirequire/#l).

**Comment by heymartinadams** [comment]
Also, here: https://github.com/auth0/wt-cli/issues/141

**Comment by dbismut** [comment]
@ggoodman hey - any plans to add the `transform-runtime` to the webpack config as suggested in the issue mentioned by @heymartinadams above?

Also @mrwillis if you use the sandbox environment from Webtask as [explained here](https://tomasz.janczuk.org/2017/09/auth0-webtasks-and-node-8.html) you can use Node 8 ;)

**Comment by NotMyself** [comment]
Hi Everyone,

Webtask.io now runs on Node 8 directly. Async/Away is supported. I am going to close this issue. Feel free to respond and reopen if you have any questions.

**Comment by wearhere** [comment]
Hey @NotMyself, should this be supported now?

```js
module.exports = async function(context) {
  return { hello: context.query.name || 'Jeff' };
};
```

It seems to time out.

**Comment by NotMyself** [comment]
Hi @wearhere,

I think the bare minimum async webtask would look like this:

```javascript
module.exports = async function(context, cb) {
  const example = await Promise.resolve({
    hello: context.query.name || 'Anonymous'
  });
  cb(null, example);
};
```

In your example code, the context parameter will actually be a callback function not the webtask context. See the [programming models documentation](https://webtask.io/docs/model) for details.

In my example, we use the `async` keyword to enable us to use `await` sematics within the body of the function. You still need to resolve the function using the callback function.

**Comment by wearhere** [comment]
Ah thanks for clarifying current support. I filed https://github.com/auth0/webtask-bundle/issues/31 as a follow-up.

**Comment by mortezae** [comment]
I found a mistake regarding this issue in webtask web interface:
Create new > Select a template > Async function
You'll see:
Instructions: Simply export an async function and return a result directly to indicate completion
Code:
```javascript
/**
* @param context {WebtaskContext}
*/
module.exports = async function (context) {
  return { hello: context.query.name || 'Anonymous' };
};
```
But this generates error and still we need call cb rather just returning
